// End-to-end verification for the /api/leads/create pipeline.
//
// What it does:
//   1. POSTs a synthetic lead to LOCAL_DEV_URL/api/leads/create
//   2. Verifies the row landed in ads.leads
//   3. Logs the CAPI response trace (events_received: 1 with a test code,
//      otherwise async — Meta processes it after the request returns)
//   4. Cleans up the synthetic row so the table stays empty
//
// Prerequisites:
//   - pnpm dev running locally (defaults to http://localhost:3000)
//   - LEADS_API_ENABLED=true in .env.local
//
// Flags:
//   SKIP_RESEND=true → sends body.__test_skip_emails so the route doesn't
//   call Resend. Use this during dry-runs to avoid spamming real inboxes.
//
// Resend message IDs are NOT printed because the route doesn't return
// them (response shape is { ok, lead_id } only). To see message IDs,
// check the dev server's console output during the POST.

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const DEV_URL = process.env.LEADS_DEV_URL ?? "http://localhost:3000";
const SKIP_RESEND = process.env.SKIP_RESEND === "true";

const TEST_EMAIL = `verify+${Date.now()}@miltonly.test`;
const TEST_PHONE = "647-555-0123";

interface PostResponse {
  ok: boolean;
  lead_id?: string;
  no_op?: boolean;
  error?: string;
}

async function main() {
  console.log("=== verify-leads-pipeline ===");
  console.log(`POST → ${DEV_URL}/api/leads/create`);
  console.log(`SKIP_RESEND=${SKIP_RESEND}`);
  console.log(`test email: ${TEST_EMAIL}`);
  console.log(`test phone: ${TEST_PHONE}`);
  console.log("");

  const body = {
    source: "organic",
    intent: "rent",
    name: "Verify Script",
    email: TEST_EMAIL,
    phone: TEST_PHONE,
    notes: `auto-generated by scripts/verify-leads-pipeline.ts at ${new Date().toISOString()}`,
    event_source_url: `${DEV_URL}/verify-test`,
    ...(SKIP_RESEND ? { __test_skip_emails: true } : {}),
  };

  // ── Step 1: POST ────────────────────────────────────────────────────
  let response: PostResponse;
  try {
    const res = await fetch(`${DEV_URL}/api/leads/create`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    const text = await res.text();
    console.log(`HTTP ${res.status} ${res.statusText}`);
    console.log(`response body: ${text}`);
    response = JSON.parse(text) as PostResponse;
    if (!res.ok) {
      console.error("POST failed");
      process.exit(1);
    }
  } catch (err) {
    console.error("POST threw — is the dev server running?", err);
    process.exit(1);
  }

  if (response.no_op) {
    console.warn("");
    console.warn("⚠ route returned no_op — LEADS_API_ENABLED is not 'true' in dev server's env");
    console.warn("  set LEADS_API_ENABLED=true in .env.local, restart pnpm dev, retry");
    process.exit(1);
  }

  if (!response.lead_id) {
    console.error("response missing lead_id");
    process.exit(1);
  }

  console.log("");
  console.log(`✓ POST succeeded, lead_id = ${response.lead_id}`);

  // ── Step 2: verify DB row ───────────────────────────────────────────
  const row = await prisma.adsLead.findUnique({ where: { id: response.lead_id } });
  if (!row) {
    console.error(`✗ no ads.leads row found for id ${response.lead_id}`);
    process.exit(1);
  }
  console.log(`✓ ads.leads row found:`);
  console.log(`    id:        ${row.id}`);
  console.log(`    source:    ${row.source}`);
  console.log(`    intent:    ${row.intent}`);
  console.log(`    email:     ${row.email}`);
  console.log(`    phone:     ${row.phone}`);
  console.log(`    createdAt: ${row.createdAt?.toISOString()}`);

  // CAPI trace is in the dev server's console (route logs failures via
  // console.warn). Successes are silent. If you want to see CAPI shape,
  // tail the dev server while running this script.
  console.log("");
  console.log("CAPI: fire-and-forget from the route — check dev server console for trace.");
  if (process.env.META_CAPI_TEST_EVENT_CODE) {
    console.log(`  META_CAPI_TEST_EVENT_CODE is set → event should appear in Events Manager's Test Events tab within ~30s`);
  } else {
    console.log(`  META_CAPI_TEST_EVENT_CODE is unset → event goes to production stream (use a test code during testing!)`);
  }

  // ── Step 3: cleanup ─────────────────────────────────────────────────
  console.log("");
  await prisma.adsLead.delete({ where: { id: response.lead_id } });
  const stillThere = await prisma.adsLead.findUnique({ where: { id: response.lead_id } });
  if (stillThere) {
    console.error(`✗ cleanup failed — row ${response.lead_id} still present`);
    process.exit(1);
  }
  console.log(`✓ cleanup successful — test row deleted`);

  console.log("");
  console.log("=== verify-leads-pipeline PASS ===");
}

main()
  .catch((err) => {
    console.error("verify-leads-pipeline threw:", err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
