import { NextRequest, NextResponse } from "next/server";
import canonicalMap from "@/lib/_generated/canonical-map.json";
import validCanonicalSlugs from "@/lib/_generated/valid-canonical-slugs.json";
import noRedirectSlugs from "@/lib/_generated/no-redirect-slugs.json";
import { deriveIdentity } from "@/lib/streetUtils";

// ============================================================
// PRE-LAUNCH GATE
// Blocks all public traffic until PropTx IDX URL approval
// for miltonly.com is granted.
//
// To DISABLE this gate (go live):
//   Set MAINTENANCE_MODE = false below, then git push.
//
// To PREVIEW the real site while gate is on:
//   Visit https://miltonly.com/?preview=miltonly-aamir-2026
//   This sets a cookie. Future visits bypass the gate.
//
// To clear preview cookie:
//   Visit https://miltonly.com/?preview=off
// ============================================================

const MAINTENANCE_MODE = false;

// Change this secret to rotate access. Anyone with the current
// secret can preview the real site.
const PREVIEW_SECRET = "miltonly-aamir-2026";

const PREVIEW_COOKIE = "miltonly_preview";

// Paths that always bypass the gate:
// - /coming-soon : the public placeholder page
// - /api/sync/*, /api/compliance/*, /api/monitor/* : nightly crons (already secret-protected)
// - /admin/*, /api/admin/* : admin panel (already password-protected)
// - /_next/*, /favicon.ico, /robots.txt, static assets
const ALWAYS_ALLOW = [
  "/coming-soon",
  "/api/sync",
  "/api/compliance",
  "/api/monitor",
  "/api/alerts",
  "/api/revalidate",
  "/admin",
  "/api/admin",
  "/api/auth",
  "/_next",
  "/favicon",
  "/robots.txt",
  "/sitemap.xml",
  "/manifest.webmanifest",
  "/opengraph-image",
];

// Step 13m-4a — static slug-to-canonical map for sibling-variant 301s on
// /streets/*. Generated by scripts/generate-canonical-map.ts from the
// universe's identity-dedupe pick rule (data-bearing slug wins; shortest
// + alphabetical tiebreak). Regenerate whenever the universe shifts.
const SLUG_TO_CANONICAL = canonicalMap as Record<string, string>;

// Valid canonical slugs (render-bearing streets + off-registry roads), emitted by
// generate-canonical-map.ts. The computed variant→canonical rule only redirects when
// the canonical is in this set — so it NEVER 301s into a 404.
const VALID_CANONICALS = new Set<string>(validCanonicalSlugs as string[]);
// Slugs that must NEVER be a redirect source: official registry streets (canonical in
// their own right — incl. the distinct directional NAMES Kennedy Circle East/West) and
// off-registry rural roads. Guarded FIRST, so nothing (static map or computed) redirects them.
const NO_REDIRECT = new Set<string>(noRedirectSlugs as string[]);

// Hub-v2 cutover — legacy /neighbourhoods/<slug> 301s. The old HubBlock route
// matched the munged Listing.neighbourhood slug forms; the new getHubData seam
// resolves only the canonical Neighbourhood.slug. These three slugs are indexed
// on prod under the legacy form, so 301 them to the canonical 200 target to
// transfer index equity. Mirrors the streetRedirect sibling→canonical pattern.
const NEIGHBOURHOOD_LEGACY_TO_CANONICAL: Record<string, string> = {
  "1051---walker": "walker",
  "brookvillehaltonville": "brookville-haltonville",
  "rural-nassagaweya": "nassagaweya",
};

// Resolve a requested /streets/[slug] to its canonical slug, or null for no redirect.
// Order of precedence (single hop, never into a 404):
//   1. Static curated map (generate-canonical-map.ts) — an override for any case the
//      computed rule would get wrong.
//   2. Off-registry rural roads (Side Roads, Second Line, Nipissing Rd) — never touched.
//   3. Computed rule — deriveIdentity's canonical (abbreviation/direction/doubled-suffix/
//      -n-a collapse). Redirect only when it differs AND resolves (VALID_CANONICALS).
function canonicalFor(slug: string): string | null {
  // 0. Official registry + off-registry slugs are canonical themselves — never redirect
  //    them (protects Kennedy Circle East/West and every rural road), regardless of map.
  if (NO_REDIRECT.has(slug)) return null;
  // 1. Static curated override.
  const mapped = SLUG_TO_CANONICAL[slug];
  if (mapped && mapped !== slug) return mapped;
  // 2. Computed rule — deriveIdentity canonical, only when it differs AND resolves.
  const id = deriveIdentity(slug);
  if (!id) return null; // malformed → let the route 404
  const canonical = id.canonicalSlug;
  if (canonical === slug) return null; // already canonical
  if (!VALID_CANONICALS.has(canonical)) return null; // never 301 into a 404
  if (NO_REDIRECT.has(canonical)) return canonical; // canonical is an official/off-reg street — fine to land there
  return canonical;
}

function streetRedirect(req: NextRequest): NextResponse | null {
  const { pathname } = req.nextUrl;
  if (!pathname.startsWith("/streets/")) return null;
  const slug = pathname.slice("/streets/".length).split("/")[0];
  if (!slug) return null;
  const canonical = canonicalFor(slug);
  if (!canonical) return null;
  const url = req.nextUrl.clone();
  url.pathname = `/streets/${canonical}`;
  return NextResponse.redirect(url, 301);
}

function neighbourhoodRedirect(req: NextRequest): NextResponse | null {
  const { pathname } = req.nextUrl;
  if (!pathname.startsWith("/neighbourhoods/")) return null;
  const slug = pathname.slice("/neighbourhoods/".length).split("/")[0];
  if (!slug) return null;
  const canonical = NEIGHBOURHOOD_LEGACY_TO_CANONICAL[slug];
  if (!canonical || canonical === slug) return null;
  const url = req.nextUrl.clone();
  url.pathname = `/neighbourhoods/${canonical}`;
  return NextResponse.redirect(url, 301);
}

export function middleware(req: NextRequest) {
  // Sibling → canonical 301 redirect runs FIRST. Applies regardless of the
  // maintenance gate because SEO / crawler consistency needs it whether
  // we're pre-launch or live.
  const redirect = streetRedirect(req) ?? neighbourhoodRedirect(req);
  if (redirect) return redirect;

  if (!MAINTENANCE_MODE) return NextResponse.next();

  const { pathname, searchParams } = req.nextUrl;

  // Handle preview toggle
  const previewParam = searchParams.get("preview");
  if (previewParam === PREVIEW_SECRET) {
    const res = NextResponse.redirect(new URL(pathname, req.url));
    res.cookies.set(PREVIEW_COOKIE, PREVIEW_SECRET, {
      httpOnly: true,
      secure: true,
      sameSite: "lax",
      maxAge: 60 * 60 * 24 * 30, // 30 days
    });
    return res;
  }
  if (previewParam === "off") {
    const res = NextResponse.redirect(new URL("/coming-soon", req.url));
    res.cookies.delete(PREVIEW_COOKIE);
    return res;
  }

  // Bypass gate if preview cookie is valid
  const previewCookie = req.cookies.get(PREVIEW_COOKIE)?.value;
  if (previewCookie === PREVIEW_SECRET) {
    return NextResponse.next();
  }

  // Always-allow paths
  if (ALWAYS_ALLOW.some((p) => pathname.startsWith(p))) {
    return NextResponse.next();
  }

  // Everyone else: rewrite to coming-soon
  return NextResponse.rewrite(new URL("/coming-soon", req.url));
}

// Narrowed to /streets/* and /neighbourhoods/* — the only production-active
// logic is the streetRedirect / neighbourhoodRedirect canonical 301s.
// If MAINTENANCE_MODE is ever flipped back to true, expand this back to the
// broad pattern ["/((?!_next/static|_next/image|favicon.ico).*)"] so the
// maintenance gate covers all routes.
export const config = {
  matcher: ["/streets/:path*", "/neighbourhoods/:path*"],
};
